### ISSUE TITLE
Switching to js_cookie_rails

### ISSUE THREAD

**Issue by gabskoro** [infinum/cookies_eu#30]
It's not so important, but maybe we could switch to [https://github.com/freego/js_cookie_rails](js_cookie_rails) because [jquery-cookie-rails](https://github.com/RyanScottLewis/jquery-cookie-rails) is no longer maintained.

**Comment by d4be4st** [comment]
Or we can just write our own, so we do not depend on jquery.

**Comment by gabskoro** [comment]
Agree, :+1: will send u a PR.

**Comment by Startouf** [comment]
It is needed for rails 5.

**Comment by d4be4st** [comment]
ping @gabskoro

**Comment by gabskoro** [comment]
Sorry guys, finally done :) #33
