### ISSUE TITLE
click on button does nothing

### ISSUE THREAD

**Issue by netiko** [infinum/cookies_eu#35]
hi,

since recently, the text and button display still well, but clicking on button does nothing
Using js_cookie_rails 2.1.3
Using cookies_eu 1.5.0

thanks

**Comment by gabskoro** [comment]
Can you please tell me on which browser are you testing it?

**Comment by vitobotta** [comment]
Hi, just noticed the same with IE 10/11 on Windows. Works fine with Edge, Firefox, Safari and Chrome.

Thanks
Vito

**Comment by gabskoro** [comment]
Ahh, IE<edge doesn't support `remove()` on nodes, it's fixed now and a new release is out :)

**Comment by netiko** [comment]
hi,
thanks for answer
i'm using ubuntu. Ive tried on chrome, chromium and firefox, and none are working

**Comment by gabskoro** [comment]
Hey Netiko, could you please try the new release and if the issue still exists just reopen the task

**Comment by netiko** [comment]
still same problem

**Comment by vitobotta** [comment]
Hi, I think it's working now on IE - thanks ! - but the banner doesn't show up in Safari? I am trying with OSX in a virtual machine and have cleared the cookies etc but it seems like it doesn't show up anymore.

**Comment by vitobotta** [comment]
In the end I implemented it from scratch as it was very simple. Thanks anyway

**Comment by netiko** [comment]
for me what is weird is that when I try on dev mode on my computer, it is working, but in prod, it is not. Can it be because of assets pipeline ? (here my website http://veux-veux-pas.fr/)

**Comment by gabskoro** [comment]
Hej guys, this should be fixed now, added support for async and defer #39

**Comment by SophiaPetrova** [comment]
Hey! I am experiencing the same issue at the moment. Click on 'OK' button works as expected locally but cannot be clicked on production.
