### ISSUE TITLE
Turbolink support is missing

### ISSUE THREAD

**Issue by toncid** [infinum/cookies_eu#4]
Great gem! :)

However, it doesn't work well with Turbolinks in Rails 4. When you switch to another page, the .click() event handler is lost and not bound again.

The JS code should be rewritten to listen for the "page:load" event as follows:

```CoffeeScript
readyFunc = ->
    $(".cookies-eu-ok").click (e) ->
        e.preventDefault();
        $.cookie('cookie_eu_consented', 'true', {path: '/', expires: 365});
        $('.cookies-eu').remove();

$(document).ready(readyFunc)
$(document).on("page:load", readyFunc)
```

**Comment by d4be4st** [comment]
Added to readme.

Thanks @toncid

**Comment by toncid** [comment]
:+1:

**Comment by zedtux** [comment]
Turbolinks is default to Rails, as @toncid said introducing yet another dependency to fix a simple thing sounds not good.

Is there any good reason to not have it?

**Comment by kaspernj** [comment]
That gem doesn't work with Turbolinks 5 according to their readme. I feel like this issue should be reopened :-)

**Comment by martyn-w** [comment]
Please consider re-opening this issue and updating the gem to support Turbolinks now that Rails 5 applications use it by default

**Comment by obromios** [comment]
I agree, particularly as [ jquery.turbolinks](https://github.com/kossnocorp/jquery.turbolinks) no longer works with rails 5+.  Give jquery.turbolinks is now deprecated, this lessens the force of d4be4st concern above that it would not be clear how the suggested modification would operate with jquery.turbolinks.

**Comment by obromios** [comment]
Does cookieconsent work with turbolinks.

**Comment by kaspernj** [comment]
@obromios Yes. I made it work with Turbolinks without any issues. Turbolinks support was the reason I switched away from `cookies_eu` in the first place :-)

**Comment by kaspernj** [comment]
@obromios You see how it works on the site I used it on here: www.peakflow.io

Here is the JavaScript I wrote for it:
```js
window.addEventListener("turbolinks:load", function(){
  window.cookieconsent.initialise({
    "palette": {
      "popup": {
        "background": "#f8f8f8"
      },
      "button": {
        "background": "#337ab7"
      }
    },
    "position": "bottom-right"
  })
})
```

**Comment by gabskoro** [comment]
Letting you know that Turbolinks support (#58) was merged, will be deployed in few minutes :)

**Comment by wrails** [comment]
I can confirm that cookies_eu still doesn't work with Rails +5. Clciking on the OK button does nothing. 
Please check.
Instead  cookie consent works perfectly straight away.
Thanks two both posts.
