### ISSUE TITLE
problem with generator cookies_eu:install

### ISSUE THREAD

**Issue by andrediascosta** [infinum/cookies_eu#42]
Hello,

I'm getting a error when installing if i have application.css.scss. The installer is expecting the file without .scss

Thanks.

**Comment by gabskoro** [comment]
@d4be4st What about adding support for this above? In general, when you're creating a new rails project you got `.scss` by default, so it makes sense to me.

**Comment by karolmajek** [comment]
Agree - generator looks for .css file.
It appends ' *= require cookies_eu' multiple times (!) at the end of every multi-line comment /**/

**Comment by gabskoro** [comment]
Added check (https://github.com/infinum/cookies_eu/commit/46ad3ea7062f11ff06c6d969d7538a1971789832), we now support `.css`, `.scss`, and `.css.scss` extensions :)
