### ISSUE TITLE
Problem with correct styling after deployment

### ISSUE THREAD

**Issue by feroiso** [infinum/cookies_eu#43]
After deployment styling disappears:
Development: http://imgur.com/a/Z0H4A
Production: http://imgur.com/a/snZlb
Button is not clickable.
All gems are properly installed.
```
js_cookie_rails (2.1.3)
cookies_eu (1.6.1)
```
Checked on Edge, Chrome and Firefox..
@Edit Fixed it, I just didn't precompile stuff, my bad.

**Comment by gabskoro** [comment]
👍
