### ISSUE TITLE
Add a screenshot to the README.md file

### ISSUE THREAD

**Issue by zedtux** [infinum/cookies_eu#53]
This is a good way to show to visitors what would add that gem to their project.

**Comment by gabskoro** [comment]
Nice idea, will do!, tnx :)

**Comment by lobner** [comment]
> Nice idea, will do!, tnx :)

Hey @gabskoro where can I find said screenshot?

**Comment by gabskoro** [comment]
> > Nice idea, will do!, tnx :)
> 
> Hey @gabskoro where can I find said screenshot?

haha, damn, already 2 years passed 😅 Will do today!

**Comment by gabskoro** [comment]
Done, check out the Readme page

**Comment by zedtux** [comment]
Thank you !

**Comment by lobner** [comment]
> > > Nice idea, will do!, tnx :)
> > 
> > 
> > Hey @gabskoro where can I find said screenshot?
> 
> haha, damn, already 2 years passed  Will do today!

Time flies :) - thx! :+1:
