### ISSUE TITLE
<%= render 'cookies_eu/consent_banner' %> doesn't render any view

### ISSUE THREAD

**Issue by dikey94** [infinum/cookies_eu#55]
I think there is sth wrong with  "<%= render 'cookies_eu/consent_banner' %>". I've put it inside my application.html.erb, I can see ' Rendered /Users/damiankulig/.rvm/gems/ruby-2.3.0/gems/cookies_eu-1.6.3/app/views/cookies_eu/_consent_banner.html.erb (1.2ms)' in logs but rendered HTML is empty.
Any advise?

**Comment by JohnSmall** [comment]
I'm getting the same problem. I can see the html in my pages, but nothing displays.

I suspect it's because Turbolinks is messing with the Javascript code. 

This seems to be a very old gem that needs to be updated for Turbolinks >= 5.x

**Comment by gabskoro** [comment]
Hmm, Turbolinks shouldn't do anything. Do you still have the problem? Are you sure that the cookie isn't already saved? (name: cookie_eu_consented)

**Comment by brian5150** [comment]
I have the same issue and also see the following in my log file:
Rendered /home/brian/.rbenv/versions/2.2.9/lib/ruby/gems/2.2.0/gems/cookies_eu-1.7.1/app/views/cookies_eu/_consent_banner.html.erb (1.9ms)

My code in the view is:

    <p>Start</p>
    <%= render 'cookies_eu/consent_banner' %>
    <p>End</p>

And the browsers does indeed display the "Start" and "End" wrappers.

Any ideas?

**Comment by jpjofre94** [comment]
Yep, having the same issue

**Comment by JaisonBrooks** [comment]
[Non relevant question] What IDE is that from the screenshots above?

**Comment by gabskoro** [comment]
Visual Studio Code (https://code.visualstudio.com) with the Dark+ and Material icon theme :)

**Comment by brian5150** [comment]
Same problem in incognito mode on Chrome.

**Comment by beaudenon** [comment]
Same problem - we solved by changing the name of a page called "cookies" (view/action)

**Comment by magicrubyf** [comment]
Well yes here is the issue :
If you define the method
```
class HomeController < ApplicationController
  def cookies
  end
end
```
in order to have the view, then any path of controller '/home/..' will not render the banner.
1st solution change the name of method as beaudenon mentioned.
2st solution create an independent controller.

**Comment by gabskoro** [comment]
Wow, what an edge case :) Will definitely fix that, tnx!
