### ISSUE TITLE
jquery-turbolinks gem does not work with Rails 5+

### ISSUE THREAD

**Issue by obromios** [infinum/cookies_eu#57]
Looking at issue #4, it appears a decision was made not to support turbolinks because the addition of of the jquery-turbolinks gem allows cookie_eu to work with turbolinks. 

However, jquery-turbolinks is now [deprecated](https://github.com/kossnocorp/jquery.turbolinks), in particular it does not work with rails 5+.

I have implemented cookie_eu with rails 5.1.4 and the jquery-turbolinks gem and find that cookie_eu does not function properly. If you go directly to a page that is meant to show the cookie, then clicking on the OK button does hide the cookie warning. However, if you to click to the same page by following a link from another page, although the cookie warning message is displayed,  clicking on the OK button does nothing.  If I am correct, this will also happen for existing users of cookie_eu who upgrade to rails 5+.

I am hoping this can be fixed as I think this a useful gem, particularly with the imminent need to comply with the GPDR.

**Comment by gabskoro** [comment]
Hey, Turbolinks support was added :) 

And yeah, adding `jquery-turbolinks` won't fix anything because around two years ago we removed jQuery completely, so it also never worked with an older version of Turbolinks (`jquery-turbolinks` listens for jquery's ready event)
