### ISSUE TITLE
Is this gem working on Rails 4.1.5?

### ISSUE THREAD

**Issue by raulgarciadev** [infinum/cookies_eu#6]
Hi I've just installed the gem using bundler and following the steps in the readme and I'm getting some errors `couldn't find file 'cookies_eu'` in application.js, it seems that the gem did not added the required files to the project. I tried to install the gem using 

    gem 'cookies_eu',git: 'git://github.com/infinum/cookies_eu.git'

but this did not solved the issue, what am I doing wrong? 
any suggestion?
Thx.

**Comment by d4be4st** [comment]
Did you try restarting the server after bundle installing?
I just tried to install it on 4.1.5 and everything worked fine.
You need to restart your server/pow after adding a new assets gem so rails knows about the new files

**Comment by raulgarciadev** [comment]
OMG this is embarrassing... 

Sometimes it's really hard to be newbie.

Thx.

**Comment by d4be4st** [comment]
No problem. we all did that mistake :)
