### ISSUE TITLE
Make the view customizable

### ISSUE THREAD

**Issue by surfermicha** [infinum/cookies_eu#68]
It would be great if you could make the view customizable like in the Devise gem, where you can optionally change the HTML code.

**Comment by relaxsergey** [comment]
> It would be great if you could make the view customizable like in the Devise gem, where you can optionally change the HTML code.

create folder cookies_eu in views.
create partial consent_banner.html.erb

copy this

```
<% if cookies && cookies['cookie_eu_consented'] != 'true' %>
  <div class="cookies-eu js-cookies-eu">
    <span class="cookies-eu-content-holder"><%= t('cookies_eu.cookies_text') %></span>
    <span class="cookies-eu-button-holder">
    <button class="cookies-eu-ok js-cookies-eu-ok"> <%= t('cookies_eu.ok') %> </button>
    <% if defined?(link).present? %>
      <a href="<%= link %>" class="cookies-eu-link" target="<%= defined?(target).present? ? target : '' %>"> <%= t('cookies_eu.learn_more') %> </a>
    <% end %>
    </span>
  </div>
<% end %>
```

and customize.

**Comment by MatthiasHertel** [comment]
the filename from the partial should be: `_consent_banner.html.erb` dont forget the leading underscore!

**Comment by gabskoro** [comment]
Tnx @relaxsergey, I added the description to the readme
