### ISSUE TITLE
generator appended on last line not new line

### ISSUE THREAD

**Issue by mysticaltech** [infinum/cookies_eu#71]
Hello, just to signal that on lastest Rails 5.2.2, the generator appended both for js and scss on the last line, not a new line. Like so:

```
@import '@fortawesome/fontawesome-free/css/all.min.css';@import 'cookies_eu';
```

**Comment by gabskoro** [comment]
Tested on RoR 6.0.2 and looks fine again, so not worth spending time on that :)
