### ISSUE TITLE
Slovenian locale file name

### ISSUE THREAD

**Issue by toncid** [infinum/cookies_eu#8]
Language code for [Slovene](http://en.wikipedia.org/wiki/Slovene_language) is `sl`, not `si` ([Sinhala](http://en.wikipedia.org/wiki/Sinhala_language)).

Thanks! :-)

**Comment by d4be4st** [comment]
fixed, released 1.0.14

**Comment by toncid** [comment]
The `si` in the locale file needs to be changed to `sl` as well.

```
si:  # <===
  cookies_eu:
    ...
```

**Comment by d4be4st** [comment]
bah, thx

**Comment by toncid** [comment]
:+1:

**Comment by toncid** [comment]
Another rerelease? :)

**Comment by toncid** [comment]
Thanks :)

**Comment by d4be4st** [comment]
yes :+1: 
1.0.15
