### ISSUE TITLE
Support for persisting acknowledgement with a user account?

### ISSUE THREAD

**Issue by jfly** [infinum/cookies_eu#90]
If someone is logged in when they acknowledge the banner, it would be nice to store that acknowledgement in the database so we don't keep hounding the same person to re-acknowledge the same thing over and over again as they log into different devices.

I understand that this wouldn't make sense to implement in a turnkey way, but it would be nice if this gem provided a hook to run some arbitrary javascript code when someone clicks the "ok" button. Then we could do something like make an API call to record the user's preference in the database and not render the banner if the user is logged in and has already acknowledged the cookie law.

Would you be open to a PR adding a callback to the [`cookiesEu.init` method](https://github.com/infinum/cookies_eu/blob/3f91806082a8044723a139bf79165cb558856ac6/app/assets/javascripts/cookies_eu.js#L7), or is that out of scope for this package?

**Comment by gabskoro** [comment]
Personally, I don't see a reason why we shouldn't add that to the library. Feel free to open a PR :)

**Comment by jfly** [comment]
Thanks for the quick merge and quick release on rubygems!
